package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"gft/internal/task/graph"
	"gft/internal/task/model"
)

// FindTaskByID is the resolver for the findTaskByID field.
func (r *entityResolver) FindTaskByID(ctx context.Context, id string) (*model.Task, error) {
	return r.Query().Task(ctx, id)
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
