package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"gft/internal/task"
	"gft/internal/task/graph"
	"gft/internal/task/model"
	"strings"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	t, _, found := strings.Cut(id, ":")
	if !found {
		return nil, fmt.Errorf("failed to extract type from id: %s", id)
	}

	switch t {
	case task.Type:
		return r.Task(ctx, id)
	default:
		return nil, fmt.Errorf("unsupported type: %s", t)
	}
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	t, err := r.Repo.GetByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get a task by id: %s with error: %w", id, err)
	}

	return t, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	return r.Repo.GetAll(), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
