// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Query struct {
}

type Task struct {
	ID string `json:"id"`
}

func (Task) IsEntity() {}
