// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Query struct {
}

type Task struct {
	ID string `json:"id"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Tasks []*Task `json:"tasks"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }
