package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"gft/internal/user"
	"gft/internal/user/graph"
	"gft/internal/user/model"
	"strings"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.Repo.GetAll(), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	u, err := r.Repo.GetByID(id)
	if err != nil {
		return nil, fmt.Errorf("failed to get by id: %w", err)
	}
	return u, nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (model.Node, error) {
	t, _, found := strings.Cut(id, ":")
	if !found {
		return nil, fmt.Errorf("failed to extract type from id: %s", id)
	}

	switch t {
	case user.Type:
		return r.User(ctx, id)
	default:
		return nil, fmt.Errorf("unsupported type: %s", t)
	}
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
