// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Query struct {
}

type Task struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (Task) IsNode()            {}
func (this Task) GetID() string { return this.ID }
